server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beyond-eyesight/bintegration
          skipSslValidation: true
          default-label: develop
          search-paths: config/src/main/resources/config/*
        accept-empty: false






