server:
  port: 8888

spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beyond-eyesight/bintegration
#          todo: 'src/main/resources/config'를 따로 뺄 수 있는지 확인.
          searchPaths: config/src/main/resources/config/fellowshipservice
        default-label: develop
      label: develop






