server:
  port: 8888

spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beyond-eyesight/bintegration
          repos:
            fellowship:
              pattern: fellowship*/dev*,fellowship*/local*,fellowship*/prod*
              uri: https://github.com/beyond-eyesight/bintegration
              searchPaths: config/src/main/resources/config/fellowship
              default-label: develop

        default-label: develop
      label: develop






