spring:
  cloud:
    gateway:
      routes:
        # SockJS route
        - id: websocket_sockjs_route
          uri: http://52.78.142.210:8080
          # todo: sockjs로 테스트 해보기
          predicates:
            - Path=/ws-stomp/**
        # Normal Websocket route
        - id: websocket_route
          uri: ws://52.78.142.210:8080
          predicates:
            - Path=/ws-stomp/**
        - id: chat_route
          uri: http://52.78.142.210:8080
          predicates:
            - Path=/chat/**
