spring:
  cloud:
    gateway:
      routes:
        # SockJS route
        - id: websocket_sockjs_route
          uri: lb://FELLOWSHIP:8080
          # todo: sockjs로 테스트 해보기
          predicates:
            - Path=/ws-stomp/**
        # Normal Websocket route
        - id: websocket_route
          uri: lb:ws://FELLOWSHIP:8080
          predicates:
            - Path=/ws-stomp/**
        - id: chat_route
          uri: lb://FELLOWSHIP:8080
          predicates:
            - Path=/chat/**
