version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
#    volumes:
#      - ./out/cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
#    deploy:
#      resources:
#        limits:
#          memory: 1000M
#        reservations:
#          memory: 500M
  fellowship:
    image: beyondeyesight/fellowship:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - cassandra
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8080"
      CASSANDRA_PORT: "9042"
      REDIS_PORT:          "6379"




