spring:
  datasource:
    url: jdbc:mysql://test-access-1.cuwocpon5oew.ap-northeast-2.rds.amazonaws.com:3306/access
    username: beyondeyesight
    password: '{cipher}1656fb032f87c963aac5930523bc4e928e574adf530eba8ab64faabf6e40bbe9'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
