spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beyondeyesight
    username: beyondeyesight
    password: ttkmw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
