server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/beyond-eyesight/config.git
          search-paths: chatservice
          username: beyond-eyesight
          password: chillvibe

encrypt:
  key: IMSTMMETRIC


