spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beyondeyesight
    username: ttkmw
    password: ttkmw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
