spring:
  profiles:
    active: alpha
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
