spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  data:
    cassandra:
      contact-points: localhost
      port: 9142
      keyspace-name: testKeySpace
      local-datacenter: datacenter1
