server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/beyond-eyesight/config/
          search-paths: chatservice
          username: beyond-eyesight
          password: chillvibe


