spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://3.36.97.51:8888/
      label: develop
      fail-fast: true
      enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
