spring:
  datasource:
    url: jdbc:mysql://bintegration.cuwocpon5oew.ap-northeast-2.rds.amazonaws.com:3306/access
    username: beyondeyesight
    password: todo_config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
