spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
      label: develop
  datasource:
    url: jdbc:mysql://localhost:3306/beyondeyesight
    username: beyondeyesight
    password: ttkmw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
#  security-constraints:
#    - auth-roles:
#      - user
#    - security-collections:
#      - patterns:
#        - /customer/*


#    securityCollections:
#      patterns: /customer/*

#    securityCollections[0]:
#      patterns[0]: /customer/*
#    auth-roles[0]: user



#    patterns[0]: /customer/*


eureka:
  instance:
    prefer-ip-address: true # 서비스 이름 대신 서비스 IP 주소 등록
  client:
    register-with-eureka: true # 유레카에 서비스 등록
    fetch-registry: true # 유레카 클라이언트가 레지스트리의 복사본을 가져오도록 지정. true로 설정 시 검색할 때마다 유레카 서비스를 호출하는 대신 레지스트리가 로컬로 캐시된다. 30초마다 클라이언트는 유레카 서비스에 레지스트리 변경 사항 여부를 재확인한다.
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
