spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/
      label: develop
      fail-fast: true
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/beyondeyesight
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
