spring:
  redis:
    host: redis
    port: 6379

  data:
    cassandra:
      contact-points: cassandra.ap-northeast-2.amazonaws.com
      port: 9142
      keyspace-name: testkeyspace
      local-datacenter: ap-northeast-2
      ssl: true
      # todo: config 서버로 옮길 때 새로 생성하기
      username: geunwonlim-at-174579883227
      password: "{cipher}f7db090d30ae34b305825eb2b9cebbfa65f95191ece65fa7fb27871ba62f1c2283f5ba95cb069639130398b15949dc5437e49d31e5e336b37a377b52103897b7"
      request:
        consistency: local_quorum
