version: "3"
services:
  fellowship:
    image: beyondeyesight/fellowship:latest
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8080"
      CASSANDRA_PORT: "9042"
      REDIS_PORT:          "6379"




