spring:
  redis:
    host: redis
    port: 6379

  data:
    cassandra:
      contact-points: cassandra.ap-northeast-2.amazonaws.com
      port: 9142
      keyspace-name: testkeyspace
      local-datacenter: ap-northeast-2
      ssl: true
      username: geunwonlim-at-174579883227
      password: pgDHHX7h+cYB/MFR2zZehK9WeYLxNyQU8DeytO0YshI=
