spring:
  redis:
    host: bintegration-redis.15uxi6.0001.apn2.cache.amazonaws.com
    port: 6379

  data:
    cassandra:
      contact-points: cassandra.ap-northeast-2.amazonaws.com
      port: 9142
      keyspace-name: testkeyspace
      local-datacenter: ap-northeast-2
      ssl: true
