server:
  port: 8080

spring:
  application:
    name: fellowship
  profiles:
    active: dev

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
