# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Manual - Java CI with Gradle

on:
   workflow_dispatch:
     inputs:
       name:
         description: 'service name'
         required: true
         default: ''
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x ${{ github.event.inputs.name }}/gradlew
      - name: Build with Gradle
        run: ./${{ github.event.inputs.name }}/gradlew build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACESS_TOKEN }}
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./${{ github.event.inputs.name }}
          file: ./${{ github.event.inputs.name }}/Dockerfile
          tags: beyondeyesight/fellowship:latest
          push: true
